### PR TITLE
Python CSTR simulator

### PR DESCRIPTION
**Pull request by octavio-santiago**
Python version of the CSTR simulator adapted to Bonsai. Including the simulator and files to send to an ACR container and train a Bonsai brain.

### CODE REVIEW

**Review by scotstan — COMMENTED** [review]
Can you add a short README.md to this folder to describe how to run?

And rename the folder "Python" to lower-case "python"

**Comment by octavio-santiago** [comment]
Done.
The requested files have been added to the branch and the folder now is in lower-case.

**Comment by scotstan** [comment]
`bonsai-common` is not supported. Can you port to use `microsoft-bonsai-api`?

See these docs:
https://docs.microsoft.com/en-us/bonsai/resources/open-source-tools

**Comment by scotstan** [comment]
Not ready to merge into `main` yet, so I made a new branch `pythonsim` for this PR. You should be able to fork and push back changes to this new branch directly.

**Pull request closed without merging**
